// apps/wishlister-service/internal/proto/wish.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: wish.proto

package wish

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWishRequest) Reset() {
	*x = CreateWishRequest{}
	mi := &file_wish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishRequest) ProtoMessage() {}

func (x *CreateWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishRequest.ProtoReflect.Descriptor instead.
func (*CreateWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateWishRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWishRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateWishRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateWishRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateWishRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type GetWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WishId        int64                  `protobuf:"varint,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishRequest) Reset() {
	*x = GetWishRequest{}
	mi := &file_wish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishRequest) ProtoMessage() {}

func (x *GetWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishRequest.ProtoReflect.Descriptor instead.
func (*GetWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{1}
}

func (x *GetWishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetWishRequest) GetWishId() int64 {
	if x != nil {
		return x.WishId
	}
	return 0
}

type UpdateWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WishId        int64                  `protobuf:"varint,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	UpdateData    map[string]string      `protobuf:"bytes,3,rep,name=update_data,json=updateData,proto3" json:"update_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWishRequest) Reset() {
	*x = UpdateWishRequest{}
	mi := &file_wish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWishRequest) ProtoMessage() {}

func (x *UpdateWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWishRequest.ProtoReflect.Descriptor instead.
func (*UpdateWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWishRequest) GetWishId() int64 {
	if x != nil {
		return x.WishId
	}
	return 0
}

func (x *UpdateWishRequest) GetUpdateData() map[string]string {
	if x != nil {
		return x.UpdateData
	}
	return nil
}

type DeleteWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WishId        int64                  `protobuf:"varint,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWishRequest) Reset() {
	*x = DeleteWishRequest{}
	mi := &file_wish_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishRequest) ProtoMessage() {}

func (x *DeleteWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteWishRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteWishRequest) GetWishId() int64 {
	if x != nil {
		return x.WishId
	}
	return 0
}

type ListWishesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWishesRequest) Reset() {
	*x = ListWishesRequest{}
	mi := &file_wish_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishesRequest) ProtoMessage() {}

func (x *ListWishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishesRequest.ProtoReflect.Descriptor instead.
func (*ListWishesRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{4}
}

func (x *ListWishesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWishesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWishesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareLinkRequest) Reset() {
	*x = CreateShareLinkRequest{}
	mi := &file_wish_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkRequest) ProtoMessage() {}

func (x *CreateShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShareLinkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateShareLinkRequest) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GetSharedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharedRequest) Reset() {
	*x = GetSharedRequest{}
	mi := &file_wish_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedRequest) ProtoMessage() {}

func (x *GetSharedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharedRequest.ProtoReflect.Descriptor instead.
func (*GetSharedRequest) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{6}
}

func (x *GetSharedRequest) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

type WishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishResponse) Reset() {
	*x = WishResponse{}
	mi := &file_wish_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishResponse) ProtoMessage() {}

func (x *WishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishResponse.ProtoReflect.Descriptor instead.
func (*WishResponse) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{7}
}

func (x *WishResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WishResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WishResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WishResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WishResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *WishResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *WishResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *WishResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WishResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WishResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WishListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wishes        []*WishResponse        `protobuf:"bytes,1,rep,name=wishes,proto3" json:"wishes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishListResponse) Reset() {
	*x = WishListResponse{}
	mi := &file_wish_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishListResponse) ProtoMessage() {}

func (x *WishListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishListResponse.ProtoReflect.Descriptor instead.
func (*WishListResponse) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{8}
}

func (x *WishListResponse) GetWishes() []*WishResponse {
	if x != nil {
		return x.Wishes
	}
	return nil
}

func (x *WishListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareLinkResponse) Reset() {
	*x = ShareLinkResponse{}
	mi := &file_wish_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareLinkResponse) ProtoMessage() {}

func (x *ShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareLinkResponse.ProtoReflect.Descriptor instead.
func (*ShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{9}
}

func (x *ShareLinkResponse) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *ShareLinkResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_wish_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wish_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_wish_proto_rawDescGZIP(), []int{10}
}

var File_wish_proto protoreflect.FileDescriptor

const file_wish_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wish.proto\x12\x04wish\"\xc7\x01\n" +
	"\x11CreateWishRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"B\n" +
	"\x0eGetWishRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\awish_id\x18\x02 \x01(\x03R\x06wishId\"\xce\x01\n" +
	"\x11UpdateWishRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\awish_id\x18\x02 \x01(\x03R\x06wishId\x12H\n" +
	"\vupdate_data\x18\x03 \x03(\v2'.wish.UpdateWishRequest.UpdateDataEntryR\n" +
	"updateData\x1a=\n" +
	"\x0fUpdateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x11DeleteWishRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\awish_id\x18\x02 \x01(\x03R\x06wishId\"Z\n" +
	"\x11ListWishesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"P\n" +
	"\x16CreateShareLinkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"3\n" +
	"\x10GetSharedRequest\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\"\x90\x02\n" +
	"\fWishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"_\n" +
	"\x10WishListResponse\x12*\n" +
	"\x06wishes\x18\x01 \x03(\v2\x12.wish.WishResponseR\x06wishes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"S\n" +
	"\x11ShareLinkResponse\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"\x0f\n" +
	"\rEmptyResponse2\xc0\x03\n" +
	"\vWishService\x129\n" +
	"\n" +
	"CreateWish\x12\x17.wish.CreateWishRequest\x1a\x12.wish.WishResponse\x123\n" +
	"\aGetWish\x12\x14.wish.GetWishRequest\x1a\x12.wish.WishResponse\x129\n" +
	"\n" +
	"UpdateWish\x12\x17.wish.UpdateWishRequest\x1a\x12.wish.WishResponse\x12:\n" +
	"\n" +
	"DeleteWish\x12\x17.wish.DeleteWishRequest\x1a\x13.wish.EmptyResponse\x12=\n" +
	"\n" +
	"ListWishes\x12\x17.wish.ListWishesRequest\x1a\x16.wish.WishListResponse\x12H\n" +
	"\x0fCreateShareLink\x12\x1c.wish.CreateShareLinkRequest\x1a\x17.wish.ShareLinkResponse\x12A\n" +
	"\x0fGetSharedWishes\x12\x16.wish.GetSharedRequest\x1a\x16.wish.WishListResponseB\tZ\a../wishb\x06proto3"

var (
	file_wish_proto_rawDescOnce sync.Once
	file_wish_proto_rawDescData []byte
)

func file_wish_proto_rawDescGZIP() []byte {
	file_wish_proto_rawDescOnce.Do(func() {
		file_wish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wish_proto_rawDesc), len(file_wish_proto_rawDesc)))
	})
	return file_wish_proto_rawDescData
}

var file_wish_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wish_proto_goTypes = []any{
	(*CreateWishRequest)(nil),      // 0: wish.CreateWishRequest
	(*GetWishRequest)(nil),         // 1: wish.GetWishRequest
	(*UpdateWishRequest)(nil),      // 2: wish.UpdateWishRequest
	(*DeleteWishRequest)(nil),      // 3: wish.DeleteWishRequest
	(*ListWishesRequest)(nil),      // 4: wish.ListWishesRequest
	(*CreateShareLinkRequest)(nil), // 5: wish.CreateShareLinkRequest
	(*GetSharedRequest)(nil),       // 6: wish.GetSharedRequest
	(*WishResponse)(nil),           // 7: wish.WishResponse
	(*WishListResponse)(nil),       // 8: wish.WishListResponse
	(*ShareLinkResponse)(nil),      // 9: wish.ShareLinkResponse
	(*EmptyResponse)(nil),          // 10: wish.EmptyResponse
	nil,                            // 11: wish.UpdateWishRequest.UpdateDataEntry
}
var file_wish_proto_depIdxs = []int32{
	11, // 0: wish.UpdateWishRequest.update_data:type_name -> wish.UpdateWishRequest.UpdateDataEntry
	7,  // 1: wish.WishListResponse.wishes:type_name -> wish.WishResponse
	0,  // 2: wish.WishService.CreateWish:input_type -> wish.CreateWishRequest
	1,  // 3: wish.WishService.GetWish:input_type -> wish.GetWishRequest
	2,  // 4: wish.WishService.UpdateWish:input_type -> wish.UpdateWishRequest
	3,  // 5: wish.WishService.DeleteWish:input_type -> wish.DeleteWishRequest
	4,  // 6: wish.WishService.ListWishes:input_type -> wish.ListWishesRequest
	5,  // 7: wish.WishService.CreateShareLink:input_type -> wish.CreateShareLinkRequest
	6,  // 8: wish.WishService.GetSharedWishes:input_type -> wish.GetSharedRequest
	7,  // 9: wish.WishService.CreateWish:output_type -> wish.WishResponse
	7,  // 10: wish.WishService.GetWish:output_type -> wish.WishResponse
	7,  // 11: wish.WishService.UpdateWish:output_type -> wish.WishResponse
	10, // 12: wish.WishService.DeleteWish:output_type -> wish.EmptyResponse
	8,  // 13: wish.WishService.ListWishes:output_type -> wish.WishListResponse
	9,  // 14: wish.WishService.CreateShareLink:output_type -> wish.ShareLinkResponse
	8,  // 15: wish.WishService.GetSharedWishes:output_type -> wish.WishListResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wish_proto_init() }
func file_wish_proto_init() {
	if File_wish_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wish_proto_rawDesc), len(file_wish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wish_proto_goTypes,
		DependencyIndexes: file_wish_proto_depIdxs,
		MessageInfos:      file_wish_proto_msgTypes,
	}.Build()
	File_wish_proto = out.File
	file_wish_proto_goTypes = nil
	file_wish_proto_depIdxs = nil
}
