// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: wish.proto

package wish

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WishService_CreateWish_FullMethodName      = "/wish.WishService/CreateWish"
	WishService_GetWish_FullMethodName         = "/wish.WishService/GetWish"
	WishService_UpdateWish_FullMethodName      = "/wish.WishService/UpdateWish"
	WishService_DeleteWish_FullMethodName      = "/wish.WishService/DeleteWish"
	WishService_ListWishes_FullMethodName      = "/wish.WishService/ListWishes"
	WishService_CreateShareLink_FullMethodName = "/wish.WishService/CreateShareLink"
	WishService_GetShareLinks_FullMethodName   = "/wish.WishService/GetShareLinks"
	WishService_GetSharedWishes_FullMethodName = "/wish.WishService/GetSharedWishes"
	WishService_DeleteShareLink_FullMethodName = "/wish.WishService/DeleteShareLink"
)

// WishServiceClient is the client API for WishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WishServiceClient interface {
	CreateWish(ctx context.Context, in *CreateWishRequest, opts ...grpc.CallOption) (*WishResponse, error)
	GetWish(ctx context.Context, in *GetWishRequest, opts ...grpc.CallOption) (*WishResponse, error)
	UpdateWish(ctx context.Context, in *UpdateWishRequest, opts ...grpc.CallOption) (*WishResponse, error)
	DeleteWish(ctx context.Context, in *DeleteWishRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ListWishes(ctx context.Context, in *ListWishesRequest, opts ...grpc.CallOption) (*WishListResponse, error)
	CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*ShareLinkResponse, error)
	GetShareLinks(ctx context.Context, in *GetShareLinksRequest, opts ...grpc.CallOption) (*ShareLinksResponse, error)
	GetSharedWishes(ctx context.Context, in *GetSharedRequest, opts ...grpc.CallOption) (*WishListResponse, error)
	DeleteShareLink(ctx context.Context, in *DeleteShareLinkRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type wishServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWishServiceClient(cc grpc.ClientConnInterface) WishServiceClient {
	return &wishServiceClient{cc}
}

func (c *wishServiceClient) CreateWish(ctx context.Context, in *CreateWishRequest, opts ...grpc.CallOption) (*WishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishResponse)
	err := c.cc.Invoke(ctx, WishService_CreateWish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) GetWish(ctx context.Context, in *GetWishRequest, opts ...grpc.CallOption) (*WishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishResponse)
	err := c.cc.Invoke(ctx, WishService_GetWish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) UpdateWish(ctx context.Context, in *UpdateWishRequest, opts ...grpc.CallOption) (*WishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishResponse)
	err := c.cc.Invoke(ctx, WishService_UpdateWish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) DeleteWish(ctx context.Context, in *DeleteWishRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WishService_DeleteWish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) ListWishes(ctx context.Context, in *ListWishesRequest, opts ...grpc.CallOption) (*WishListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishListResponse)
	err := c.cc.Invoke(ctx, WishService_ListWishes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) CreateShareLink(ctx context.Context, in *CreateShareLinkRequest, opts ...grpc.CallOption) (*ShareLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareLinkResponse)
	err := c.cc.Invoke(ctx, WishService_CreateShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) GetShareLinks(ctx context.Context, in *GetShareLinksRequest, opts ...grpc.CallOption) (*ShareLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareLinksResponse)
	err := c.cc.Invoke(ctx, WishService_GetShareLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) GetSharedWishes(ctx context.Context, in *GetSharedRequest, opts ...grpc.CallOption) (*WishListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishListResponse)
	err := c.cc.Invoke(ctx, WishService_GetSharedWishes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishServiceClient) DeleteShareLink(ctx context.Context, in *DeleteShareLinkRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, WishService_DeleteShareLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WishServiceServer is the server API for WishService service.
// All implementations must embed UnimplementedWishServiceServer
// for forward compatibility.
type WishServiceServer interface {
	CreateWish(context.Context, *CreateWishRequest) (*WishResponse, error)
	GetWish(context.Context, *GetWishRequest) (*WishResponse, error)
	UpdateWish(context.Context, *UpdateWishRequest) (*WishResponse, error)
	DeleteWish(context.Context, *DeleteWishRequest) (*EmptyResponse, error)
	ListWishes(context.Context, *ListWishesRequest) (*WishListResponse, error)
	CreateShareLink(context.Context, *CreateShareLinkRequest) (*ShareLinkResponse, error)
	GetShareLinks(context.Context, *GetShareLinksRequest) (*ShareLinksResponse, error)
	GetSharedWishes(context.Context, *GetSharedRequest) (*WishListResponse, error)
	DeleteShareLink(context.Context, *DeleteShareLinkRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedWishServiceServer()
}

// UnimplementedWishServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWishServiceServer struct{}

func (UnimplementedWishServiceServer) CreateWish(context.Context, *CreateWishRequest) (*WishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWish not implemented")
}
func (UnimplementedWishServiceServer) GetWish(context.Context, *GetWishRequest) (*WishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWish not implemented")
}
func (UnimplementedWishServiceServer) UpdateWish(context.Context, *UpdateWishRequest) (*WishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWish not implemented")
}
func (UnimplementedWishServiceServer) DeleteWish(context.Context, *DeleteWishRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWish not implemented")
}
func (UnimplementedWishServiceServer) ListWishes(context.Context, *ListWishesRequest) (*WishListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWishes not implemented")
}
func (UnimplementedWishServiceServer) CreateShareLink(context.Context, *CreateShareLinkRequest) (*ShareLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShareLink not implemented")
}
func (UnimplementedWishServiceServer) GetShareLinks(context.Context, *GetShareLinksRequest) (*ShareLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShareLinks not implemented")
}
func (UnimplementedWishServiceServer) GetSharedWishes(context.Context, *GetSharedRequest) (*WishListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSharedWishes not implemented")
}
func (UnimplementedWishServiceServer) DeleteShareLink(context.Context, *DeleteShareLinkRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShareLink not implemented")
}
func (UnimplementedWishServiceServer) mustEmbedUnimplementedWishServiceServer() {}
func (UnimplementedWishServiceServer) testEmbeddedByValue()                     {}

// UnsafeWishServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WishServiceServer will
// result in compilation errors.
type UnsafeWishServiceServer interface {
	mustEmbedUnimplementedWishServiceServer()
}

func RegisterWishServiceServer(s grpc.ServiceRegistrar, srv WishServiceServer) {
	// If the following call pancis, it indicates UnimplementedWishServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WishService_ServiceDesc, srv)
}

func _WishService_CreateWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).CreateWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_CreateWish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).CreateWish(ctx, req.(*CreateWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_GetWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).GetWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_GetWish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).GetWish(ctx, req.(*GetWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_UpdateWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).UpdateWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_UpdateWish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).UpdateWish(ctx, req.(*UpdateWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_DeleteWish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).DeleteWish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_DeleteWish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).DeleteWish(ctx, req.(*DeleteWishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_ListWishes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWishesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).ListWishes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_ListWishes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).ListWishes(ctx, req.(*ListWishesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_CreateShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).CreateShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_CreateShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).CreateShareLink(ctx, req.(*CreateShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_GetShareLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).GetShareLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_GetShareLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).GetShareLinks(ctx, req.(*GetShareLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_GetSharedWishes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).GetSharedWishes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_GetSharedWishes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).GetSharedWishes(ctx, req.(*GetSharedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishService_DeleteShareLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShareLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishServiceServer).DeleteShareLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishService_DeleteShareLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishServiceServer).DeleteShareLink(ctx, req.(*DeleteShareLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WishService_ServiceDesc is the grpc.ServiceDesc for WishService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WishService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wish.WishService",
	HandlerType: (*WishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWish",
			Handler:    _WishService_CreateWish_Handler,
		},
		{
			MethodName: "GetWish",
			Handler:    _WishService_GetWish_Handler,
		},
		{
			MethodName: "UpdateWish",
			Handler:    _WishService_UpdateWish_Handler,
		},
		{
			MethodName: "DeleteWish",
			Handler:    _WishService_DeleteWish_Handler,
		},
		{
			MethodName: "ListWishes",
			Handler:    _WishService_ListWishes_Handler,
		},
		{
			MethodName: "CreateShareLink",
			Handler:    _WishService_CreateShareLink_Handler,
		},
		{
			MethodName: "GetShareLinks",
			Handler:    _WishService_GetShareLinks_Handler,
		},
		{
			MethodName: "GetSharedWishes",
			Handler:    _WishService_GetSharedWishes_Handler,
		},
		{
			MethodName: "DeleteShareLink",
			Handler:    _WishService_DeleteShareLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wish.proto",
}
