// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: filer.proto

package filer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilerService_LoadImage_FullMethodName = "/filer.FilerService/LoadImage"
)

// FilerServiceClient is the client API for FilerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilerServiceClient interface {
	LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error)
}

type filerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilerServiceClient(cc grpc.ClientConnInterface) FilerServiceClient {
	return &filerServiceClient{cc}
}

func (c *filerServiceClient) LoadImage(ctx context.Context, in *LoadImageRequest, opts ...grpc.CallOption) (*LoadImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadImageResponse)
	err := c.cc.Invoke(ctx, FilerService_LoadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilerServiceServer is the server API for FilerService service.
// All implementations must embed UnimplementedFilerServiceServer
// for forward compatibility.
type FilerServiceServer interface {
	LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error)
	mustEmbedUnimplementedFilerServiceServer()
}

// UnimplementedFilerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilerServiceServer struct{}

func (UnimplementedFilerServiceServer) LoadImage(context.Context, *LoadImageRequest) (*LoadImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedFilerServiceServer) mustEmbedUnimplementedFilerServiceServer() {}
func (UnimplementedFilerServiceServer) testEmbeddedByValue()                      {}

// UnsafeFilerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilerServiceServer will
// result in compilation errors.
type UnsafeFilerServiceServer interface {
	mustEmbedUnimplementedFilerServiceServer()
}

func RegisterFilerServiceServer(s grpc.ServiceRegistrar, srv FilerServiceServer) {
	// If the following call pancis, it indicates UnimplementedFilerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilerService_ServiceDesc, srv)
}

func _FilerService_LoadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilerServiceServer).LoadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilerService_LoadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilerServiceServer).LoadImage(ctx, req.(*LoadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilerService_ServiceDesc is the grpc.ServiceDesc for FilerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filer.FilerService",
	HandlerType: (*FilerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadImage",
			Handler:    _FilerService_LoadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filer.proto",
}
