// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: filer.proto

package filer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageBase64   string                 `protobuf:"bytes,1,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageRequest) Reset() {
	*x = LoadImageRequest{}
	mi := &file_filer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageRequest) ProtoMessage() {}

func (x *LoadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageRequest.ProtoReflect.Descriptor instead.
func (*LoadImageRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{0}
}

func (x *LoadImageRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

type LoadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageResponse) Reset() {
	*x = LoadImageResponse{}
	mi := &file_filer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageResponse) ProtoMessage() {}

func (x *LoadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageResponse.ProtoReflect.Descriptor instead.
func (*LoadImageResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{1}
}

func (x *LoadImageResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_filer_proto protoreflect.FileDescriptor

const file_filer_proto_rawDesc = "" +
	"\n" +
	"\vfiler.proto\x12\x05filer\"5\n" +
	"\x10LoadImageRequest\x12!\n" +
	"\fimage_base64\x18\x01 \x01(\tR\vimageBase64\"0\n" +
	"\x11LoadImageResponse\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl2N\n" +
	"\fFilerService\x12>\n" +
	"\tLoadImage\x12\x17.filer.LoadImageRequest\x1a\x18.filer.LoadImageResponseB\n" +
	"Z\b../filerb\x06proto3"

var (
	file_filer_proto_rawDescOnce sync.Once
	file_filer_proto_rawDescData []byte
)

func file_filer_proto_rawDescGZIP() []byte {
	file_filer_proto_rawDescOnce.Do(func() {
		file_filer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filer_proto_rawDesc), len(file_filer_proto_rawDesc)))
	})
	return file_filer_proto_rawDescData
}

var file_filer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filer_proto_goTypes = []any{
	(*LoadImageRequest)(nil),  // 0: filer.LoadImageRequest
	(*LoadImageResponse)(nil), // 1: filer.LoadImageResponse
}
var file_filer_proto_depIdxs = []int32{
	0, // 0: filer.FilerService.LoadImage:input_type -> filer.LoadImageRequest
	1, // 1: filer.FilerService.LoadImage:output_type -> filer.LoadImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filer_proto_init() }
func file_filer_proto_init() {
	if File_filer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filer_proto_rawDesc), len(file_filer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filer_proto_goTypes,
		DependencyIndexes: file_filer_proto_depIdxs,
		MessageInfos:      file_filer_proto_msgTypes,
	}.Build()
	File_filer_proto = out.File
	file_filer_proto_goTypes = nil
	file_filer_proto_depIdxs = nil
}
