/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegistrationImport } from './routes/registration'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppWishlistImport } from './routes/app.wishlist'
import { Route as AppSettingsImport } from './routes/app.settings'
import { Route as AppFriendsImport } from './routes/app.friends'
import { Route as AppCreateImport } from './routes/app.create'

// Create/Update Routes

const RegistrationRoute = RegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppWishlistRoute = AppWishlistImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppFriendsRoute = AppFriendsImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)

const AppCreateRoute = AppCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateImport
      parentRoute: typeof AppImport
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsImport
      parentRoute: typeof AppImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/app/wishlist': {
      id: '/app/wishlist'
      path: '/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AppWishlistImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWishlistRoute: typeof AppWishlistRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWishlistRoute: AppWishlistRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishlist': typeof AppWishlistRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishlist': typeof AppWishlistRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/app/create': typeof AppCreateRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishlist': typeof AppWishlistRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/app/create'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/app/create'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishlist'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/app/create'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishlist'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegistrationRoute: typeof RegistrationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegistrationRoute: RegistrationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/login",
        "/logout",
        "/registration"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/create",
        "/app/friends",
        "/app/settings",
        "/app/wishlist"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/registration": {
      "filePath": "registration.tsx"
    },
    "/app/create": {
      "filePath": "app.create.tsx",
      "parent": "/app"
    },
    "/app/friends": {
      "filePath": "app.friends.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app.settings.tsx",
      "parent": "/app"
    },
    "/app/wishlist": {
      "filePath": "app.wishlist.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
