/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharelistRouteImport } from './routes/sharelist'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppWishesIndexRouteImport } from './routes/app/wishes/index'
import { Route as AppWishesCreateRouteImport } from './routes/app/wishes/create'
import { Route as AppWishesIdIndexRouteImport } from './routes/app/wishes/$id/index'
import { Route as AppWishesIdUpdateRouteImport } from './routes/app/wishes/$id/update'
import { Route as AppWishesIdEditRouteImport } from './routes/app/wishes/$id/edit'

const SharelistRoute = SharelistRouteImport.update({
  id: '/sharelist',
  path: '/sharelist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWishesIndexRoute = AppWishesIndexRouteImport.update({
  id: '/wishes/',
  path: '/wishes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWishesCreateRoute = AppWishesCreateRouteImport.update({
  id: '/wishes/create',
  path: '/wishes/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWishesIdIndexRoute = AppWishesIdIndexRouteImport.update({
  id: '/wishes/$id/',
  path: '/wishes/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWishesIdUpdateRoute = AppWishesIdUpdateRouteImport.update({
  id: '/wishes/$id/update',
  path: '/wishes/$id/update',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWishesIdEditRoute = AppWishesIdEditRouteImport.update({
  id: '/wishes/$id/edit',
  path: '/wishes/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/sharelist': typeof SharelistRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishes/create': typeof AppWishesCreateRoute
  '/app/wishes': typeof AppWishesIndexRoute
  '/app/wishes/$id/edit': typeof AppWishesIdEditRoute
  '/app/wishes/$id/update': typeof AppWishesIdUpdateRoute
  '/app/wishes/$id': typeof AppWishesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/sharelist': typeof SharelistRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishes/create': typeof AppWishesCreateRoute
  '/app/wishes': typeof AppWishesIndexRoute
  '/app/wishes/$id/edit': typeof AppWishesIdEditRoute
  '/app/wishes/$id/update': typeof AppWishesIdUpdateRoute
  '/app/wishes/$id': typeof AppWishesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/registration': typeof RegistrationRoute
  '/sharelist': typeof SharelistRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wishes/create': typeof AppWishesCreateRoute
  '/app/wishes/': typeof AppWishesIndexRoute
  '/app/wishes/$id/edit': typeof AppWishesIdEditRoute
  '/app/wishes/$id/update': typeof AppWishesIdUpdateRoute
  '/app/wishes/$id/': typeof AppWishesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/sharelist'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishes/create'
    | '/app/wishes'
    | '/app/wishes/$id/edit'
    | '/app/wishes/$id/update'
    | '/app/wishes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/sharelist'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishes/create'
    | '/app/wishes'
    | '/app/wishes/$id/edit'
    | '/app/wishes/$id/update'
    | '/app/wishes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/logout'
    | '/registration'
    | '/sharelist'
    | '/app/friends'
    | '/app/settings'
    | '/app/wishes/create'
    | '/app/wishes/'
    | '/app/wishes/$id/edit'
    | '/app/wishes/$id/update'
    | '/app/wishes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegistrationRoute: typeof RegistrationRoute
  SharelistRoute: typeof SharelistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sharelist': {
      id: '/sharelist'
      path: '/sharelist'
      fullPath: '/sharelist'
      preLoaderRoute: typeof SharelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wishes/': {
      id: '/app/wishes/'
      path: '/wishes'
      fullPath: '/app/wishes'
      preLoaderRoute: typeof AppWishesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wishes/create': {
      id: '/app/wishes/create'
      path: '/wishes/create'
      fullPath: '/app/wishes/create'
      preLoaderRoute: typeof AppWishesCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wishes/$id/': {
      id: '/app/wishes/$id/'
      path: '/wishes/$id'
      fullPath: '/app/wishes/$id'
      preLoaderRoute: typeof AppWishesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wishes/$id/update': {
      id: '/app/wishes/$id/update'
      path: '/wishes/$id/update'
      fullPath: '/app/wishes/$id/update'
      preLoaderRoute: typeof AppWishesIdUpdateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wishes/$id/edit': {
      id: '/app/wishes/$id/edit'
      path: '/wishes/$id/edit'
      fullPath: '/app/wishes/$id/edit'
      preLoaderRoute: typeof AppWishesIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppFriendsRoute: typeof AppFriendsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWishesCreateRoute: typeof AppWishesCreateRoute
  AppWishesIndexRoute: typeof AppWishesIndexRoute
  AppWishesIdEditRoute: typeof AppWishesIdEditRoute
  AppWishesIdUpdateRoute: typeof AppWishesIdUpdateRoute
  AppWishesIdIndexRoute: typeof AppWishesIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFriendsRoute: AppFriendsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWishesCreateRoute: AppWishesCreateRoute,
  AppWishesIndexRoute: AppWishesIndexRoute,
  AppWishesIdEditRoute: AppWishesIdEditRoute,
  AppWishesIdUpdateRoute: AppWishesIdUpdateRoute,
  AppWishesIdIndexRoute: AppWishesIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegistrationRoute: RegistrationRoute,
  SharelistRoute: SharelistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
