services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data # Постоянное хранилище
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
