services:
  auth-db:
    image: postgres:17-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_service
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - birthdaywish
  wish-db:
    image: postgres:17-alpine
    container_name: wish-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wish_service
    ports:
      - "5434:5432"
    volumes:
      - wish_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - birthdaywish

  filer-db:
    image: minio/minio
    container_name: filer-db
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - filer_db_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: server /data --console-address ":9001"
    networks:
      - birthdaywish

  auth-service:
    build:
      dockerfile: apps/auth/Dockerfile
    container_name: auth-service
    ports:
      - "50051:50051"
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - birthdaywish

  wishlister-service:
    build:
      dockerfile: apps/wishlister/Dockerfile
    container_name: wishlister-service
    ports:
      - "50052:50052"
    depends_on:
      wish-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - birthdaywish

  filer-service:
    build:
      dockerfile: apps/filer/Dockerfile
    container_name: filer-service
    ports:
      - "50053:50053"
    depends_on:
      filer-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - birthdaywish

  gateway-service:
    build:
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "3030:3030"
    depends_on:
      filer-service:
        condition: service_started
      auth-service:
        condition: service_started
      wishlister-service:
        condition: service_started
    restart: unless-stopped
    networks:
      - birthdaywish
      
networks:
  birthdaywish:
    driver: bridge

volumes:
  auth_db_data:
    driver: local
  wish_db_data:
    driver: local
  filer_db_data:
    driver: local