version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - db_network

  minio:
    image: minio/minio
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - ${PGADMIN_PORT:-8080}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    networks:
      - db_network

volumes:
  db_data:
  minio_data:

networks:
  db_network:
    driver: bridge
